services:
  flask:
    build: .
    container_name: media-server
    volumes:
      - ./web:/usr/src/web
      -  ./media:/home/media
    restart : always
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "127.0.0.1:8088:80"
    restart : always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      -  ./media:/home/media
    depends_on:
      - flask
